name: VRChat インスタンス情報収集

# スケジュール設定: 毎日午前9時に実行 (UTC)
on:
  schedule:
    - cron: '0 0 * * *'  # UTC時間の毎日0時（日本時間9時）に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  fetch-instance-info:
    runs-on: ubuntu-latest
    
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4
      
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      
      - name: antfu/niのインストール
        run: npm install -g @antfu/ni
      
      - name: 依存関係のインストール
        run: nci
      
      - name: VRChatインスタンス情報スクリプトの実行
        id: fetch_data
        run: nr start
        env:
          # GitHub Secretsから認証情報を取得
          VRC_AUTH_TOKEN: ${{ secrets.VRC_AUTH_TOKEN }}
          # データディレクトリを指定
          OUTPUT_BASE_DIR: ${{ github.workspace }}
      
      - name: lint, format
        run: nr lint:fix
      
      - name: Git ユーザー設定
        if: env.FILE_CHANGED == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: 変更の確認
        id: git_status
        if: env.FILE_CHANGED == 'true'
        run: |
          git status --porcelain
          echo "HAS_CHANGES=$(git status --porcelain | wc -l | xargs)" >> $GITHUB_ENV
      
      - name: 変更をコミット
        if: env.FILE_CHANGED == 'true' && env.HAS_CHANGES != '0'
        run: |
          git add data/
          current_date=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "データ更新: $current_date"
      
      - name: GitHubにプッシュ
        if: env.FILE_CHANGED == 'true' && env.HAS_CHANGES != '0'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
